/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ItemsRequestBuilderNavigationMetadata, type ItemsRequestBuilder } from './items/';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /drives/{drive-id}
 */
export interface DriveItemRequestBuilder extends BaseRequestBuilder<DriveItemRequestBuilder> {
    /**
     * The items property
     */
    get items(): ItemsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const DriveItemRequestBuilderUriTemplate = "{+baseurl}/drives/{drive%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DriveItemRequestBuilderNavigationMetadata: Record<Exclude<keyof DriveItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    items: {
        navigationMetadata: ItemsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
